test_app:
  script:
    - . ${HOME}/lalsuite-install/etc/lalapps-user-env.sh
    - ${HOME}/anaconda2/bin/python tests.py Writer
    - ${HOME}/anaconda2/bin/python tests.py par
    - ${HOME}/anaconda2/bin/python tests.py BaseSearchClass
    - ${HOME}/anaconda2/bin/python tests.py ComputeFstat
    - ${HOME}/anaconda2/bin/python tests.py SemiCoherentSearch
    - ${HOME}/anaconda2/bin/python tests.py SemiCoherentGlitchSearch
    - ${HOME}/anaconda2/bin/python tests.py MCMCSearch
    - ${HOME}/anaconda2/bin/python tests.py GridSearch
