test_app:
  script: 
    - /home/greg/anaconda2/bin/python tests.py TestWriter
    - /home/greg/anaconda2/bin/python tests.py TestBaseSearchClass
    - /home/greg/anaconda2/bin/python tests.py TestComputeFstat
    - /home/greg/anaconda2/bin/python tests.py TestSemiCoherentGlitchSearch
