test_app:
  script:
    - . /home/user1/lalsuite-install/etc/lalapps-user-env.sh
    - /home/user1/anaconda2/bin/python tests.py Writer
    - /home/user1/anaconda2/bin/python tests.py par
    - /home/user1/anaconda2/bin/python tests.py BaseSearchClass
    - /home/user1/anaconda2/bin/python tests.py ComputeFstat
    - /home/user1/anaconda2/bin/python tests.py SemiCoherentSearch
    - /home/user1/anaconda2/bin/python tests.py SemiCoherentGlitchSearch
    - /home/user1/anaconda2/bin/python tests.py MCMCSearch
    - /home/user1/anaconda2/bin/python tests.py GridSearch
